// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SitemaTurnos.DBContext;

#nullable disable

namespace SistemaTurnos.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20230625222128_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("SitemaTurnos.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdClient")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumOfPeople")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TableRestaurantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TableRestaurantId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateReservation = new DateTime(2023, 6, 26, 19, 21, 27, 843, DateTimeKind.Local).AddTicks(3114),
                            IdClient = 1,
                            IdTable = 1,
                            NumOfPeople = 2,
                            ReservStatus = 1
                        },
                        new
                        {
                            Id = 2,
                            DateReservation = new DateTime(2023, 6, 27, 19, 21, 27, 843, DateTimeKind.Local).AddTicks(3133),
                            IdClient = 2,
                            IdTable = 2,
                            NumOfPeople = 4,
                            ReservStatus = 1
                        },
                        new
                        {
                            Id = 3,
                            DateReservation = new DateTime(2023, 6, 28, 19, 21, 27, 843, DateTimeKind.Local).AddTicks(3136),
                            IdClient = 3,
                            IdTable = 3,
                            NumOfPeople = 3,
                            ReservStatus = 1
                        },
                        new
                        {
                            Id = 4,
                            DateReservation = new DateTime(2023, 6, 29, 19, 21, 27, 843, DateTimeKind.Local).AddTicks(3137),
                            IdClient = 4,
                            IdTable = 4,
                            NumOfPeople = 6,
                            ReservStatus = 1
                        });
                });

            modelBuilder.Entity("SitemaTurnos.Entities.TableRestaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Disponibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TablesRestaurant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 4,
                            Disponibility = 0
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 3,
                            Disponibility = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 2,
                            Disponibility = 1
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 1,
                            Disponibility = 2
                        });
                });

            modelBuilder.Entity("SitemaTurnos.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            LastName = "Doe",
                            Name = "John",
                            Password = "1234",
                            UserType = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "emma.smith@example.com",
                            LastName = "Smith",
                            Name = "Emma",
                            Password = "1234",
                            UserType = "Client"
                        },
                        new
                        {
                            Id = 3,
                            Email = "michael.johnson@example.com",
                            LastName = "Johnson",
                            Name = "Michael",
                            Password = "1234",
                            UserType = "Client"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sophia.brown@example.com",
                            LastName = "Brown",
                            Name = "Sophia",
                            Password = "1234",
                            UserType = "Admin"
                        },
                        new
                        {
                            Id = 5,
                            Email = "robert.lee@example.com",
                            LastName = "Lee",
                            Name = "Robert",
                            Password = "1234",
                            UserType = "Manager"
                        });
                });

            modelBuilder.Entity("SitemaTurnos.Entities.Reservation", b =>
                {
                    b.HasOne("SitemaTurnos.Entities.TableRestaurant", null)
                        .WithMany("Reservations")
                        .HasForeignKey("TableRestaurantId");
                });

            modelBuilder.Entity("SitemaTurnos.Entities.TableRestaurant", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
